Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,9 +3,9 @@ name: Convert Markdown to PDF
 on:
   push:
     branches:
-      - main  # Trigger the workflow on push to the main branch
+      - main
     paths:
-      - '**.md'  # Only trigger if .md files are changed
+      - '**.md'
 
 jobs:
   convert:
@@ -23,14 +23,14 @@ jobs:
     - name: Convert Markdown to PDF
       run: |
         mkdir -p pdfs
-        # Use find with -print0 and xargs -0 to handle spaces in filenames
         find . -name "*.md" -print0 | while IFS= read -r -d '' file; do
+          echo "Processing file: $file"
           pdf_name="pdfs/$(basename "$file" .md).pdf"
-          pandoc "$file" -o "$pdf_name" --pdf-engine=xelatex
+          pandoc "$file" -o "$pdf_name" --pdf-engine=xelatex || echo "Error processing $file"
         done
-        
+
     - name: Upload PDFs as artifact
       uses: actions/upload-artifact@v4
       with:
         name: pdf-files
-        path: output/
+        path: pdfs/
